swagger: "2.0"
info:
    title: Argent Bank Transaction API
    description: API model proposal for user transactions
    version: 2.0.0
    termsOfService: http://swagger.io/terms/
host: localhost:3001
basePath: /api/v2
schemes:
    - http
paths:
    /transaction:
        get:
            security:
                - Bearer: []
            tags:
                - Transaction module
            summary: Transactions Current Month API
            description: API for fetching current month transactions
            parameters:
                - in: header
                  name: Authorization
                  description: Attach Bearer JWT token
                  required: true
                  type: string
                - in: body
                  name: body
                  description: Select month to get data (if no month selected, returns the data from the current month)
                  required: false
                  schema:
                        $ref: "#/definitions/getSpecificMonthTransaction"
            produces:
                - application/json
            responses:
                "200":
                    description: User transactions retrieved successfully
                    schema:
                        $ref: "#/definitions/allTransactionsResponse"
                "400":
                    description: Invalid Fields
                "401":
                    description: Unauthorized
                "404":
                    description: Transactions not found
                "500":
                    description: Internal Server Error
        post:
            security:
                - Bearer: []
            tags:
                - Transaction module
            summary: Transaction Add API
            description: API for adding a new transaction
            parameters:
                - in: header
                  name: Authorization
                  description: Attach Bearer JWT token
                  required: true
                  type: string
                - in: body
                  name: body
                  description: Transaction info needed to create a new transaction
                  required: true
                  schema:
                      $ref: "#/definitions/addTransaction"
            produces:
                - application/json
            responses:
                "200":
                    description: Transaction added successfully
                    schema:
                        $ref: "#/definitions/SingleTransactionResponse"
                "400":
                    description: Invalid Fields
                "401":
                    description: Unauthorized
                "500":
                    description: Internal Server Error
    /transaction/{idTransaction}:
        get:
            security:
                - Bearer: []
            tags:
                - Transaction module
            summary: Transaction Show API
            description: API for showing a transaction
            parameters:
                - in: header
                  name: Authorization
                  description: Attach Bearer JWT token
                  required: true
                  type: string
                - in: path
                  name: idTransaction
                  description: Id of the transaction
                  required: true
                  type: string
            produces:
                - application/json
            responses:
                "200":
                    description: Transaction retrieved successfully
                    schema:
                        $ref: "#/definitions/SingleTransactionResponse"
                "400":
                    description: Invalid Fields
                "401":
                    description: Unauthorized
                "404":
                    description: Transaction not found
                "500":
                    description: Internal Server Error
        delete:
            security:
                - Bearer: []
            tags:
                - Transaction module
            summary: Transaction Delete API
            description: API for deleting a transaction
            parameters:
                - in: header
                  name: Authorization
                  description: Attach Bearer JWT token
                  required: true
                  type: string
                - in: path
                  name: idTransaction
                  description: Id of the transaction that needs to be deleted
                  required: true
                  type: string
            produces:
                - application/json
            responses:
                "200":
                    description: Transaction deleted successfully
                "400":
                    description: Invalid Fields
                "401":
                    description: Unauthorized
                "404":
                    description: Transaction not found
                "500":
                    description: Internal Server Error
        put:
            security:
                - Bearer: []
            tags:
                - Transaction module
            summary: Transaction Edit API
            description: API for updating a transaction
            parameters:
                - in: header
                  name: Authorization
                  description: Attach Bearer JWT token
                  required: true
                  type: string
                - in: path
                  name: idTransaction
                  description: Id of the transaction that needs to be edited
                  required: true
                  type: string
                - in: body
                  name: body
                  description: Edit transaction Category
                  required: true
                  schema:
                      $ref: "#/definitions/editTransactionResponse"
            produces:
                - application/json
            responses:
                "200":
                    description: Transaction edited successfully
                    schema:
                        $ref: "#/definitions/editTransactionResponse"
                "400":
                    description: Invalid Fields
                "401":
                    description: Unauthorized
                "404":
                    description: Transaction not found
                "500":
                    description: Internal Server Error
securityDefinitions:
    Bearer:
        type: apiKey
        name: Authorization
        in: header
definitions:
    allTransactionsResponse:
        properties:
            status:
                type: integer
            message:
                type: string
            body:
                type: object
                properties:
                    nextMonth:
                        type: string
                        description: Next month
                    data:
                        type: array
                        description: Data from the selected month
                        items:
                            $ref: "#/definitions/SingleTransactionResponse"
    SingleTransactionResponse:
        properties:
            status:
                type: integer
            message:
                type: string
            body:
                type: object
                properties:
                    id:
                        type: string
                        description: Id of the transaction
                    date:
                        type: string
                        description: Date of the transaction
                    amount:
                        type: number
                        description: Amount of the transaction
                    description:
                        type: string
                        description: Description of the transaction
                    category:
                        type: string
                        description: Category of the transaction
                    notes:
                        type: string
                        description: Notes of the transaction
    addTransaction:
        properties:
            accountId:
                type: string
                description: AccountId containing the new transaction
            amount:
                type: number
                description: Amount of the new transaction
            description:
                type: string
                description: Description of the new transaction
            category:
                type: string
                description: Category of the new transaction
            notes:
                type: string
                description: Notes of the new transaction
    editTransactionResponse:
        properties:
            category:
                type: string
                description: New category of this transaction
            note:
                type: string
                description: New category of this transaction
    getSpecificMonthTransaction:
        properties:
            month:
                type: string
                description: Month selected to retrieve the data
            
    